### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by robodude** [jackmellis/vue-inject#3]
This plugin is great and has a lot of potential. 

I was able to figure out how to get an example working by looking at the documentation on [https://www.npmjs.com/package/vue-inject](https://www.npmjs.com/package/vue-inject).

However I feel I got lucky by figuring out I needed to do something like this:

```
import Repository from "./Repository";

injector.constant('apiRoot', "http://www.fake.com/api");

injector.service('repository', ["apiRoot"], Repository);
```

Some of the examples provided feel like they jump in the middle of the implementation, leaving the setup out.

I get that this builds on top of your previous projects which have their own docs but I think it'd be great if this one could have a little more.

[https://github.com/young-steveo/bottlejs](https://github.com/young-steveo/bottlejs) is a non-vue dep injection library that has pretty good documentation.

**Comment by jackmellis** [comment]
I have added some serious documentation to the readme (I'd never really got round to finishing it) so hopefully it's a bit easier to understand its place in an application.  

Thanks for the bottlejs link, I haven't come across that before.

**Comment by robodude** [comment]
It looks great! Awesome work!
