### ISSUE TITLE
Dependency Injection Configuration Types

### ISSUE THREAD

**Issue by zoomclub** [jackmellis/vue-inject#4]
vue-inject looks like a great tool for loose coupling of application services. The documentation on the API seems clear for it's purpose, yet I'm interested in a little more of an introduction to DI. 

For instance, the following recent article gives a good overview of DI solutions and from what it describes vue-inject would be an "Auto-registration" DI Container with a "Register, Resolve, Release" pattern.

[Dependency Configuration Overview](https://dev.to/samueleresca/dependency-injection-overview)

Maybe some usage scenarios would be good to add to the documentation. For me its important to be able to inject services at runtime anywhere in the code base. From the documentation it seems that services all need to be wired in before a component is created? If so, then this would still be a "Code as configuration" solution.

**Comment by jackmellis** [comment]
Thanks for the link. I think *vue-inject* (and *jpex*) is essentially a configuration DI tool, in that your services should be registered and declared before the component is instantiated. That's just a product of following a similar design pattern to Angular.  

You can, however, inject dependencies after component creation if you inject the *$resolve* service. You can then use this to pull a service into your component at a later point. i.e:  
```javascript
{
  dependencies : '$resolve',
  methods : {
    doStuff(){
      var x = this.$resolve('myDynamicService');
      return x.dynamicFn();
    }
  }
}
```
The original thought behind this was to allow for lazy or async injection, but is that the sort of thing you had in mind?  

*vue-inject* also has an equivalent method, *get*, that you can call from outside of a component. So anywhere in your application you can do `var x = injector.get('myDynamicService');`

**Comment by jackmellis** [comment]
I should also just clarify that you can create a component definition with dependencies that haven't been registered yet, as long as the services are registered before the component is instantiated.

**Comment by zoomclub** [comment]
That is what I had in mind, thanks for the clarification. I think vue-inject adds further structure and power to Vue apps, which is great. Just one thing, it would be good if the README which is in the app could be placed on the landing page of the repo 💯

**Comment by jackmellis** [comment]
I've copied the README to the root of the repository for the sake of Github. The exact same README can also be found in the app folder which is published to npm!
