### ISSUE TITLE
Constructing dependency when injected into a component

### ISSUE THREAD

**Issue by robodude** [jackmellis/vue-inject#6]
One thing that 'feels' weird to me is the behavior of instantiating services or running factories when injecting dependencies into components.

When using dependency injection I expect the same instance of the dependency to be passed in.

For instance, I'm doing:
```
    injector.constant('firebase', firebase);
    injector.constant('firebaseConfig', firebaseConfig.data);
    injector.service('firebaseRepository', ['firebase', 'firebaseConfig'], FirebaseRepository);
```

Every component that takes in the firebaseRepository will re-instantiate re-setting its state. (In this case, firebase complains about being setup more than once).

The current work-around I'm planning on using is to define firebaseRepository as a constant.

`injector.constant('firebaseRepository', new FirebaseRepository(firebase, firebaseConfig.data));`

But that means I have to manually configure the dependencies for it.

I would suggest making services and factories return same instance. If someone really needs a new instance every time a dep is injected into a component, they'd be able to wrap that functionality.

```
    injector.factory('newPersonProvider', ["defaultName", "defaultSalary"], (defaultName, defaultSalary)=>{
        return function(){
            return new Person(defaultName, defaultSalary);
        }
    })
```

or I would suggest making new methods like

`injector.constantService('firebaseRepository', ['firebase', 'firebaseConfig'], FirebaseRepository)`
or
```
    injector.constantFactory('firebaseRepository', ['firebase', 'firebaseConfig'], (firebase, firebaseConfig)=>{
        return new FirebaseRepository(firebase, firebaseConfig);
    })
```

**Comment by jackmellis** [comment]
Hi, it is possible to configure the lifecycle of a service:  
`injector.service(...).lifecycle.application();`  

I have been in two minds over the default lifecycle for services as I'm using singletons more often than not myself.

**Comment by jackmellis** [comment]
https://github.com/jackmellis/vue-inject/blob/master/README.md#lifecycle

**Comment by robodude** [comment]
Great! Thank you
