### ISSUE TITLE
Use with Vuex

### ISSUE THREAD

**Issue by John0x** [jackmellis/vue-inject#7]
Hey, what's the best way to access the vuex store state within a service?

**Comment by jackmellis** [comment]
Assuming your code looks something like this:
```javascript
Vue.use(vuex);

var store = new vuex.Store({...});

new Vue({ store });
```
the `store` is your store instance, passing it into Vue just exposes the instance to the components.  
This means it's trivially simple to also make the store available to your *vue-inject* services:  
```javascript
Vue.use(vuex);

var store = new vuex.Store({...});

injector.constant('$store', store);

new Vue({ store });
```

and then in your service:  
```javascript
injector.service('myService', ['$store'], function($store){
  $store.state.whatever;
  $store.dispatch('some-action');
});
```
